service: interruptor
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile:

functions:
  interruptor:
    handler: index.handler
    events:
      - eventBridge:
          pattern:
            source:
              - aws.cloudwatch
            detail-type:
              - CloudWatch Alarm State Change
            detail:
              state:
                value: ["ALARM"]
            resources:
              - "arn:aws:cloudwatch:us-east-1:237976457746:alarm:composite_failure_alarm"
          input:
            enable: false
