service: consumidor-processamento
frameworkVersion: '3'

provider:
  name: aws
  profile: cloudguru
  runtime: nodejs18.x

functions:
  consumidorProcessamento:
    name: 'consumidor-processamento'
    handler: index.handler
    disableLogs: true
    role: !Sub arn:aws:iam::${AWS::AccountId}:role/dev-recorrencia
    events:
      - sqs:
          batchSize: 1
          arn:
            Fn::Join:
              - ':'
              - - arn
                - aws
                - sqs
                - Ref: AWS::Region
                - Ref: AWS::AccountId
                - dev-recorrencia

